### ISSUE TITLE
Ошибка при запуске скрипта

### ISSUE THREAD

**Issue by ElbrusClimbing** [webpractik/bitrixoa#1]
Ошибка при запуске 

php */local/vendor/bin/bitrixoa --bitrix-generate --index-mode

Exception: The "local/modules/" directory does not exist.

**Comment by mnlght** [comment]
добрый день. подскажите пжл, у вас есть путь local/modules существует?
иными словами, по каким роутам вы пытаетесь построить документацию?
если можно, в ответе прикрепите скрин фолдера папки локал, вплоть до контроллера

**Comment by Voral** [comment]
Получил такую же ошибку. Дело в том что далее это все выливается в is_dir....   (в Symfony Finder).  путь относительный и он его не находит. Каталог такой есть.

**Comment by Voral** [comment]
Полагаю, на эту же тему ошибка 
```
Warning: file_put_contents(local/bitrixoa.yaml): failed to open stream: No such file or directory
Exception: Failed to saveAs("local/bitrixoa.yaml", "yaml")

```

**Comment by Voral** [comment]
В моем случае проблема решена. Запускал из каталога local. Вышел в корень и заработало

**Comment by mnlght** [comment]
логично, что генерация будет из корня, в доке так и написано ./vendor/bin/bitrixoa   =)
рад, что у Вас завелось, закрываю тогда ишью =)
